<?php
$f[]="#!/bin/sh";
$f[]="";
$f[]="### BEGIN INIT INFO";
$f[]="# Provides:          mailgraph";
$f[]="# Required-Start:    \$local_fs \$remote_fs";
$f[]="# Required-Stop:     \$local_fs \$remote_fs";
$f[]="# Default-Start:     2 3 4 5";
$f[]="# Default-Stop:      0 1 6";
$f[]="# Short-Description: Mail statistics frontend for Postfix";
$f[]="# Description: mailgraph is a very simple mail statistics rrdtool frontend for";
$f[]="#  postfix, sendmail or exim that produces daily, weekly, monthly and";
$f[]="#  yearly graphs of received/sent and bounced/rejected mail.";
$f[]="### END INIT INFO";
$f[]="";
$f[]="MAILGRAPH_CONFIG=\"/etc/default/mailgraph\"";
$f[]="NAME=\"mailgraph\"";
$f[]="DAEMON=\"/usr/sbin/mailgraph\"";
$f[]="PID_FILE=\"/var/run/mailgraph.pid\"";
$f[]="RRD_DIR=\"/var/lib/mailgraph\"";
$f[]="";
$f[]="# Default values";
$f[]="BOOT_START=true";
$f[]="MAIL_LOG=/var/log/mail.log";
$f[]="IGNORE_LOCALHOST=false";
$f[]="EXTRA_OPTIONS=\"\"";
$f[]="HTTP_USER=www-data";
$f[]="HTTP_GROUP=www-data";
$f[]="";
$f[]="[ -r \$MAILGRAPH_CONFIG ] && . \$MAILGRAPH_CONFIG";
$f[]="[ -x \$DAEMON ] || exit 0";
$f[]="";
$f[]="[ \"\$BOOT_START\" = \"true\" ]  || exit 0";
$f[]="[ \"\$IGNORE_LOCALHOST\" = \"true\" ] && IGNORE_OPTION=\"--ignore-localhost\"";
$f[]="";
$f[]=". /lib/lsb/init-functions";
$f[]="";
$f[]="case \"\$1\" in";
$f[]="        start)";
$f[]="                # Check that the data directory is writable by the user running";
$f[]="                # the HTTP daemon";
$f[]="                if [ -d \$RRD_DIR ]; then";
$f[]="                    chown \$HTTP_USER:\$HTTP_GROUP \$RRD_DIR";
$f[]="                    chmod 755 \$RRD_DIR";
$f[]="                fi";
$f[]="";
$f[]="                log_begin_msg \"Starting \$DESC:\" \"\$NAME\"";
$f[]="                if [ -f \$PID_FILE ]; then";
$f[]="                        log_action_cont_msg \" already running\"";
$f[]="                        log_end_msg 1";
$f[]="                else";
$f[]="                        start-stop-daemon --start --quiet --background --pidfile \$PID_FILE --exec \$DAEMON -- --logfile \$MAIL_LOG --daemon --daemon_pid=\$PID_FILE --daemon_rrd=\$RRD_DIR \$IGNORE_OPTION \$EXTRA_OPTIONS";
$f[]="                        log_end_msg \$?";
$f[]="                fi";
$f[]="        ;;";
$f[]="        stop)";
$f[]="                log_begin_msg \"Stopping \$DESC:\" \"\$NAME\"";
$f[]="                start-stop-daemon --stop --pidfile \$PID_FILE";
$f[]="                rm -f \$PID_FILE";
$f[]="                log_end_msg \$?";
$f[]="        ;;";
$f[]="        status)";
$f[]="                status_of_proc \"\$DAEMON\" \"\$NAME\" && exit 0 || exit \$?";
$f[]="        ;;";
$f[]="        restart|force-reload)";
$f[]="                \$0 stop";
$f[]="                \$0 start";
$f[]="        ;;";
$f[]="        *)";
$f[]="                echo \"Usage: \$SCRIPTNAME {start|stop|status|restart|force-reload}\" >&2";
$f[]="                exit 3";
$f[]="        ;;";
$f[]="esac";
$f[]="";