<?php
include_once(dirname(__FILE__)."/ressources/class.template-admin.inc");if(!isset($GLOBALS["CLASS_SOCKETS"])){if(!class_exists("sockets")){include_once("/usr/share/artica-postfix/ressources/class.sockets.inc");}$GLOBALS["CLASS_SOCKETS"]=new sockets();}
include_once(dirname(__FILE__)."/ressources/class.computers.inc");
if(isset($_GET["verbose"])){$GLOBALS["VERBOSE"]=true;ini_set('display_errors', 1);ini_set('error_reporting', E_ALL);ini_set('error_prepend_string',null);ini_set('error_append_string',null);}

if(isset($_GET["popup"])){popup();exit;}
if(isset($_POST["dhcpfixed"])){save();exit;}
js();


function js(){
	$tpl=new template_admin();
	$title=$tpl->javascript_parse_text("{new_computer}");
	$page=CurrentPageName();
    $ff=array();
    if(isset($_GET["hostname"])){$ff[]="hostname=".urlencode($_GET["hostname"]);}
    if(isset($_GET["mac"])){$ff[]="mac=".urlencode($_GET["mac"]);}
    if(isset($_GET["ipaddr"])){$ff[]="ipaddr=".urlencode($_GET["ipaddr"]);}
    if(isset($_GET["dhcpfixed"])){$ff[]="dhcpfixed=1";}
    if(isset($_GET["CallBackFunction"])){$ff[]="CallBackFunction=".urlencode($_GET["CallBackFunction"]);}


	$tpl->js_dialog3($title, "$page?popup=yes&".@implode("&",$ff));
	
}

function CallBack(){
    $CallBackFunction=trim(base64_decode($_GET["CallBackFunction"]));
    $CallBackFunction_text="blur()";
    if($CallBackFunction<>null){
        if(strpos($CallBackFunction,")")==0){
            $CallBackFunction_text="$CallBackFunction()";
        }else{
            $CallBackFunction_text=$CallBackFunction;
        }
    }
    if($CallBackFunction_text=="()"){$CallBackFunction_text=null;}
    return $CallBackFunction_text;
}

function popup(){
    $EnableSquidMicroHotSpot=intval($GLOBALS["CLASS_SOCKETS"]->GET_INFO("EnableSquidMicroHotSpot"));
    $EnableDHCPServer=intval($GLOBALS["CLASS_SOCKETS"]->GET_INFO("EnableDHCPServer"));
    $EnableKEA=intval($GLOBALS["CLASS_SOCKETS"]->GET_INFO("EnableKEA"));
    if($EnableKEA==1){
        $Interfaces=kea_interfaces2();
        $EnableDHCPServer=1;
    }
	$explain=null;
	$tpl=new template_admin();
	$ip=new IP();
    $dhcpfixed=0;
    if(isset($_GET["dhcpfixed"])){
        $dhcpfixed=1;
    }

    foreach ($_GET as $key=>$val){
        VERBOSE("$key ===&laquo;[$val]",__LINE__);
    }

	if($ip->isValid($_GET["hostname"])){
		$_GET["ipaddr"]=$_GET["hostname"];
        VERBOSE("Resolv {$_GET["ipaddr"]}",__LINE__);
		$_GET["hostname"]=gethostbyaddr($_GET["ipaddr"]);
	}else{
		if($ip->IsvalidMAC($_GET["hostname"])){
			$_GET["mac"]=$_GET["hostname"];
			$_GET["hostname"]=null;
		}else{

            if($_GET["ipaddr"]==null){
                VERBOSE("Resolv {$_GET["hostname"]}",__LINE__);
                $_GET["ipaddr"]=$GLOBALS["CLASS_SOCKETS"]->gethostbyname($_GET["hostname"]);
            }
		}
	}
	
	//
	if($_GET["mac"]==null){
		$explain="{autogenerated_mac_explain}";
		$_GET["mac"]=implode(':',str_split(str_pad(base_convert(mt_rand(0,0xffffff),10,16).base_convert(mt_rand(0,0xffffff),10,16),12),2));}
	$form[]=$tpl->field_text("mac","{MAC}",$_GET["mac"],false);
	$macid=md5("mac$tpl->suffixid");
    $EnableDNSDist=intval($GLOBALS["CLASS_SOCKETS"]->GET_INFO("EnableDNSDist"));



	if($EnableDHCPServer==1){
        $form[]=$tpl->field_checkbox("dhcpfixed","{dhcpfixed}",$dhcpfixed);

        if($EnableKEA==1){
            $form[]=$tpl->field_array_hash($Interfaces,"dhcpiface","DHCP","");
        }

    }else{
	    $tpl->field_hidden("dhcpfixed",0);
    }
    if($EnableSquidMicroHotSpot==1){
        $form[]=$tpl->field_checkbox("hotspotwhite","{hotspotwhite}");
    }else{
        $tpl->field_hidden("hotspotwhite",0);
    }

    if($EnableDNSDist==1){
        $form[] = $tpl->field_checkbox("dnsfixed", "{dns_entry}");
    }


	$form[]=$tpl->field_text("fullhostname", "{hostname}", $_GET["hostname"],true);
	$form[]=$tpl->field_ipaddr("ipaddr", "{ipaddr}", $_GET["ipaddr"]);
	$form[]=$tpl->field_text("proxyalias", "{proxy_alias}", null,false,"{my_proxy_aliases_text}");
	$form[]=$tpl->field_text("hostalias1", "{alias} 1", null);
	$form[]=$tpl->field_text("hostalias2", "{alias} 2", null);
	$form[]=$tpl->field_text("hostalias3", "{alias} 3", null);
	$form[]=$tpl->field_text("hostalias4", "{alias} 4", null);

    $CallBackFunction_text=CallBack();
	$script="
		var mac=document.getElementById('$macid').value;
		dialogInstance3.close();
		Loadjs('fw.edit.computer.php?mac='+mac);
		if(document.getElementById('table-loader-my-computers')){ TableLoaderMyComputerSearch(); }	
		$CallBackFunction_text;
		";
	
	$html[]=$tpl->form_outside("{new_computer}",@implode("\n", $form),$explain,"{add}",$script,"computer");
	echo $tpl->_ENGINE_parse_body(@implode("\n", $html));
	
}
function kea_interfaces2():array{
    $net=new networking();
    $interfaces=$net->Local_interfaces();
    $MAIN=array();
    foreach ($interfaces as $interface=>$Ipaddress){
        $dhcpd=new dhcpd(0,1,$interface);
        if($dhcpd->service_enabled==0){
            continue;
        }
        $MAIN[$interface]="$dhcpd->subnet/$dhcpd->netmask";
    }
return $MAIN;
}

function save(){
	$tpl=new template_admin();
    $tpl->CLEAN_POST_XSS();
	if(trim($_POST["mac"])==null){
		$_POST["mac"]=implode(':',str_split(str_pad(base_convert(mt_rand(0,0xffffff),10,16).base_convert(mt_rand(0,0xffffff),10,16),12),2));
	}
	

	$_POST["mac"]=str_replace("-", ":", $_POST["mac"]);
	$_POST["mac"]=strtolower($_POST["mac"]);
    $q=new postgres_sql();



	$ipClass=new IP();
	if(!$ipClass->IsvalidMAC($_POST["mac"])){
		echo "MAC: {$_POST["mac"]} Invalid!\n";
		return;
	}

	if(!$ipClass->isValid($_POST["ipaddr"])){
		$_POST["ipaddr"]="0.0.0.0";
		
	}
	
	if($_POST["fullhostname"]==null){
		echo "Hostname: {$_POST["fullhostname"]} Invalid!\n";
		return;
	}

	if($_POST["dhcpfixed"]==1){
		include_once('ressources/class.dhcpd.inc');
		$dhcp=new dhcpd();
		$_POST["gateway"]=$dhcp->gateway;
		$_POST["dns1"]=$dhcp->DNS_1;
		$_POST["dns2"]=$dhcp->DNS_2;
	}


	$host=new hosts($_POST["mac"]);
	reset($_POST);

	foreach ($_POST as $key=>$val){
		$val=strtolower(trim($val));
		$host->$key=$val;

	}
	writelogs("{$_POST["mac"]},{$_POST["fullhostname"]} -> SAVE",__FUNCTION__,__FILE__,__LINE__);
	$host->Save();
	if(!$host->ok){echo $host->mysql_error;}
}